[package]
name = "evil-bit"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
arbitrary = { version = "1.2.3", features = ["derive"] }
egg = "0.9.2"
rand = "0.8.5"
termcolor = "1.2.0"
